/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {},
    },
    daisyui: {
        themes: ["light", "dark", "cupcake", "wireframe",
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            {
                custom: {
                    "primary": "#8c76e0",
                    "secondary": "#beb5ff",
                    "accent": "#d2fcae",
                    "neutral": "#35233e",
                    "base-100": "#fcfcfd",
                    "info": "#85cde0",
                    "success": "#1edcbf",
                    "warning": "#9c5e07",
                    "error": "#ec7484",
                },
            }],
    },
    plugins: [require("daisyui")],
}

